[project]
name = "alarmo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13.2"
dependencies = [
    "homeassistant>=2025.7.0",
    "pytest>=8.4.0",
    "pytest-asyncio>=1.0.0",
    "pytest-homeassistant-custom-component",
    "setuptools>=80.9.0",
]
